### ISSUE TITLE
Add incremental backup for TAR

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#105]
Hi, 
Maybe it is possible to add the option on TAR for incremental backups:
http://paulwhippconsulting.com/blog/using-tar-for-full-and-incremental-backups/

Just a suggestion, not sure how can that clash with other settings on the script.

Thanks!

**Comment by hdogan** [comment]
It may be solved with GNU tar incremental dump feature.
See: https://www.gnu.org/software/tar/manual/html_node/Incremental-Dumps.html#incremental_002dop

**Comment by planetahuevo** [comment]
Any update on this? 
Thanks

**Comment by sebastianfeldmann** [comment]
Not yet, but it has moved to the top 3 todos on my "doing next list"

**Comment by planetahuevo** [comment]
Yujuu! 💃

**Comment by planetahuevo** [comment]
This could be also an option: https://www.tecmint.com/rdiff-backup-remote-incremental-backup-for-linux/

**Comment by planetahuevo** [comment]
Hi,
Do you think this will happen sometime in the future? 
I have some backups that take 2 hours and I think this could improve those timings... 

Thanks

**Comment by sebastianfeldmann** [comment]
I have a holiday coming up next week. I try to read up on this whole tar incremental topic and see what I can do :)

**Comment by planetahuevo** [comment]
Thank you very much for taking time into this. Let me know how can I help, debugging or whatever you need.

**Comment by sebastianfeldmann** [comment]
Impelementing the `tar` part was easy. I'm still struggling with the `level zero` option that in my opinion has to be there.

`tar` offers a nice option to force a full size backup even if the incremental option is set. This way I only have to add `--level=0` and tar will create a full backup. The thing I'm struggling with is: How to configure this in user land?

```xml
<backup type="tar">
    <option name="incrementalMetadataFile" value="my-dir-cache.snar" />
    <option name="forceLevelZeroOn" value="????" />
</backup>
```

The problem here is I have no idea of the backup schedule so it could make sense to make a level zero backup every Monday, every 1st of the month, every 3am backup....

I was thinking about something like

```xml
    <option name="forceLevelZeroTrigger" value="%d" />
    <option name="forceLevelZeroOn" value="1" />
```

Then I could check if `date('d')` returns `1` and then force a level zero backup.
But splitting this up in two options feels bad. The alternative is to define a custom format like this

```xml
    <option name="forceLevelZeroOn" value="%d@1" />
```

So we could force level 0 backups like this:
- **%h@3** => always at 3am
- **%d@1** => first each month
- **%D@Mon** => all monday backups
- ...

This feels better but still a bit dirty. But I think this is the only way we can handle all possible schedules. What do you think?

**Comment by planetahuevo** [comment]
I am not sure I am understanding this right. I think that you are overthinking this with dates. The level 0 or level 1 dates and time is cron territory imho.
I think phpbu needs to check existing files the same way tar does and rely on that, and not dates or times. 

I do not see myself going deeper than level 1 in reality. Level 2 and above complicate restoration a lot, so they are not worth it really (again, this in my opinion). 

I have not going further on this, but this is what I had in mind: 
- Level 1 every day. 
- Level 0 one day of the week. 

On Phpbu backup I imagine it like this: 

Options: 
- Incremental Tar ON-OFF: to activate or not the incremental.
- Level0 Metadafilename. : the filename to use for level 0 backups. level0.snar
- LevelX metadataFilename: the filename to use for level 1 backups. level1.snar (or level X, see below)
- Which Level Are we backing up? - I suggest 3 options here: 
   A)- level 0
   B)- Level 1 (requires a level0 file first)
   C)- incremental always (first will be 1, then 2, then 3, etc). I think this complicate all the process a lot so I suggest we start with A) and B) 

With those options, the system will do (With incremental activated): 
Check level of backup we are doing.
A) Do full backup forcing level0 and create the level0 snar file using the option above. 
B) do full backup using level0 snar file and creating level 1 backup and the level1 snar file hen finished. 
C) I will leave it to the end of the document, but basically is like B but always using the level1.snar and saving the level1.snar file overriding the current.

A) process is straight forward as you say. Tou need to
I think your system will need to use a custom snar filename like phpbu-temp.snar
Do the backup using "--listed-incremental phpbu-temp.snar" always.
After the backup you (copy) move the new phpbu-temp.snar file into level0.snar

B) process is a little different. 
You again use the custom snar filename like phpbu-temp.snar
And before to start the backup, you copy the existing level0.snar into phpbu-temp.snar. (if it does not exist, you can stop with error, as the option was to do a level1, not a level0)
Do the backup using "--listed-incremental phpbu-temp.snar" 
and then when finish,  (copy) move the new phpbu-temp.snar file into level1.snar

If I want to do another backup and I decided I want level 1 again, you repeat the process, using the level0.snar and creating a new level1.snar. 

C) 
As I said before, this is kind of different, but could be done this way.
before to start the backup you copy level1.snar into phpbu-temp.snar
Do the backup using "--listed-incremental phpbu-temp.snar" (this is always the same)
and then when finish,  (copy) move the new phpbu-temp.snar file into level1.snar

This way we are overriding level1.snar file, so if I run this again and again I will be getting level 1,2,3 etc files. 
I do not know how to record this executions into the system, and this is the reason I do not think going deeper than 1 level is worth it at all, for you or for anyone using this.

Then you can add a clean or not the snar files to the cleanup.

What do you think?

**Comment by planetahuevo** [comment]
Of course this could be much easier, just setup the filename of the snar file and that will be for phpbu. 
Then let us (the user) to script the copy/move of the filenames on our script the way we prefer. 
You can add the force level0 option but not really required as removing the snar file will do the same thing.

**Comment by sebastianfeldmann** [comment]
I would argue that this feature only makes sense if we do incremental backups for a "while".
So for example if we do daily backups it would make sense to make a full backup on Sunday and every following backup for this week should be an incremental one.

This would result in:
 - Full backup on Sunday (level 0)
 - Incremental Backup with all files added or changed on Monday (level 1)
 - Incremental Backup with all files added or changed on Tuesday (level 2)
 - ... (level X)

Until on Sonday a new full backup is performed.
To restore everything you would have to keep at least 7 daily backups.

To allow multiple incremental backups in a single configuration I can't hardcode the `snar` filename.
The idea is that users have to define the `snar` file location so they can do crazy things with it if they want to. But they shouldn't have to.

To make it as easy as possible for users so they don't have to worry about setting up additional jobs to copy or do anything with the `snar` files I will most likely go with the following two configuration options.

```xml
  <option name="incrementalMetadataFile" value="my-backup.snar" />
  <option name="forceLevelZeroOn" value="%D@Sun|Wed" />
```

The configuration above would setup `phpbu` in a way that it would make full backups on Sunday and Wednesday and all other days it would do incremental backups.
So on every run the `snar` file would be updated and overwritten.

- Sun level 0
- Mon level 1
- Tue level 2
- Wed level 0
- Thu level 1
- Fri level 2
- Sat level 3

To restore everything you would have to keep at least 4 daily backups.
I think this makes the configuration values a bit more complicated because of the "crazy" format
`%TRIGGER @ VAL [|VAL]`
But I think this is the most straight forward thing we could setup that does not require a lot of manual work on the side and is still kind of "understandable".

If you want every second daily backup to be a level zero one you would have to configure something like this. Not the most intuitive way, but still the best I can think of right now.

```
  <option name="incrementalMetadataFile" value="my-backup.snar" />
  <option name="forceLevelZeroOn" value="%d@1|3|5|7|9|11|13|15|17|19|21|23|25|27|29|31" />
```

I will think about it a bit more in the next 1 or 2 days and then make a first implementation.

**Comment by planetahuevo** [comment]
I agree with that approach, but I can handle that with 2 xml phpbu backup settings like the rest of the options. 
I do not need phpbu to make it so complex because I am moving everything to a remote place anyway, so restoration won´t be automatic at all. 
So my plan was to have 2 phpbu settings, one for level 0 backups and another one for level1 backups. And I can run the level 0 us much as I want and the level 1 in between them, also as much as I want to. 
For some projects, sunday level 0 and daily level 1 makes sense, but for others, it could be once a month level 0 and daily (or weekly level1), and also daily level0 and hourly level1. 
But in the meantime, I would like to launch a manual backup before an update, that would be a level1 for me. 
What I am trying to say is that there are too many options to consider. It is impossible that you consider all options that cron allows, so I think is best just to keep it simple and let people complicate their setup as much as they (we) want. 

With my approach, you just give me the options and I can schedule then using cron, not tied to anything you have setup. 


At the moment, if you could add the 
`<option name="incrementalMetadataFile" value="my-backup.snar" />`

That will allow me to play with it, which is something I cannot do with PHPBU so far.
Can we do this in phases? 
Just add the incremental with no options to next update so we can use it and then we can dig as deep as we can on settings and configurations variations?

**Comment by planetahuevo** [comment]
Also, this makes sense for manual backups in between full backups, so it is not always needed to do backups for a while to take advantage of the incremental. 
Another case use: 
- Daily full backups at night. 
- manual level1 backups in between, only when I need to, but I know they will be much faster than the full backups so easy to execute before an update or a deployment.

**Comment by sebastianfeldmann** [comment]
I released the incremental feature with version 6.0.8

```xml
  <!-- optional, default null -->
  <option name="incrementalFile" value="path/to/metadata.snar" />

  <!-- optional, default null -->
  <option name="forceLevelZeroOn" value="%D@Sun" />
```

I You can use only the `incrementalFile` option but then you have to do all the incremental file handling yourself.
If you want `phpbu` handle level zero backups from time to time you should use `forceLevelZeroOn`

**Comment by planetahuevo** [comment]
Amazing! 
Thank you very much! 
I will do some tests as soon as I can. :)

**Comment by sebastianfeldmann** [comment]
The documentation is updated as well.
https://phpbu.de/manual/current/en/source.html#source.tar.incremental

I think the combination of `incrementalFile` and `forceLevelZeroOn` work quiet well.
You should give `forceLevelZeroOn` a try instead of doing some crazy cron and script magic ;)

**Comment by planetahuevo** [comment]
I will give it a try for sure. :) 

I do not doubt that it will work fine for backups, but makes much more complicated the full restoration (because you will need more than 2 files to do that).
I will do my crazy script magic+cron anytime if that simplify restoration for me. ;)
When you need to restore, It means that you are having an issue, so the process needs to be as fast and simple as you can. 

But I think it is great to have both options and I am sure I will use them on different use cases. 
Again thank you very much.
