### ISSUE TITLE
How do I execute phpbu from a php file?

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#106]
I am trying to make a php file to call phpbu but I am not sure how to make it work.

Any examples?

Thanks!

**Comment by sebastianfeldmann** [comment]
You could do it by calling `phpbu\App\Cmd::run($args)` with some fake `$args`

```php
<?php

require 'vendor/autoload.php';
use phpbu\App\Cmd

Cmd::run(
    [
        __FILE__
       '--configuration=' . $pathToConfigFile
    ]
);
```

If you want to have some more control have a look at the phpbu/laravel package
https://github.com/sebastianfeldmann/phpbu-laravel/blob/master/src/Cmd/Backup.php#L71

In this package I bypass the `Cmd` class and do the setup in `php`.

What you have to do:

- Setup a `phpbu\App\Runner`
- Setup a `phpbu\App\Configuration`
- Execute `$runner->run($configuration);`

In order to get some output you have to define and add some `Logger` to the `Configuration`.

By the way the same thing is done in the `phpbu\App\Cmd` class plus some command line handling
https://github.com/sebastianfeldmann/phpbu/blob/master/src/Cmd.php#L92

**Comment by planetahuevo** [comment]
The laravel and php packages goes beyond my knowledge but I will try to understand it so I can learn a little bit more with it. 
Thanks!

**Comment by sebastianfeldmann** [comment]
Let me know if this Cmd hack works, haven't tried it myself yet ;)

**Comment by eles00** [comment]
works for me:
`<?php
require 'vendor/autoload.php';

$cmd = new \phpbu\App\Cmd();
$cmd->run(
    [
        __FILE__,
       '--configuration=' . __DIR__ .  '/configuration/backup.xml'
    ]
);
`
