### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by thomasdashney** [sebastianfeldmann/phpbu#11]
When trying to install using composer, I get error messages because apparently `phpseclib/phpseclib 2.0.*@dev` doesn't exist?

```bash
$ php composer.phar require "phpbu/phpbu"
Using version ~2.0 for phpbu/phpbu
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpbu/phpbu ~2.0 -> satisfiable by phpbu/phpbu[2.0.0].
    - phpbu/phpbu 2.0.0 requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by sebastianfeldmann** [comment]
Ops... I forgot to set the dev-master branch alias.
Just updated the composer file so this should be fixed
Thanks for the report

**Comment by thomasdashney** [comment]
Happy to help! Awesome library by the way. Dropbox integration is seamless.

**Comment by sebastianfeldmann** [comment]
I just recognized that the error message you where getting is related to your own minimum stability settings.
Because of currently two libraries (phpseclib, softlayer) the phpbu minimum stability setting is set to *dev*.
So to get phpbu installed via composer you have to set you own project stability setting to dev as well.

```
"minimum-stability": "dev",
```

This is far from optimal, and for the time being I recommend to use the *PHAR* file.
I will remove the *dev* stability as soon as those two libs are available in a stable version but I can't really tell you when that is going to happen.

**Comment by thomasdashney** [comment]
Thanks for your quick response. Going to just use the PHAR file.
