### ISSUE TITLE
Restoring Backups

### ISSUE THREAD

**Issue by mablae** [sebastianfeldmann/phpbu#122]
Probably a huge task that would involve BC breaks. 

Just placing it here for discussion.

**Comment by sebastianfeldmann** [comment]
I'm currently working on a basic "restore" feature for phpbu 5.1

BUT

It will only help you restore your data and will not actually restore it.
Maybe phpbu will never do this. Let me elaborate why.

In my experience most if the time backups are needed because of human or software errors and not because of hardware failures, so it is not necessary to restore the full backup.
For example for databases it is a set of tables, a single table, or even only some rows in a table.
For files it's not the whole directory, instead it is only a special subdirectory or only some files that needs to be restored...

So the restore process is usually not to restore the whole backup.
Doing a partial restore automatically is really really difficult.

So the plan ist, to provide the user with the commands needed to restore the data, but not really executing any of them.

So `$ phpbu --restore` will output some kind of restore plan.

Decrypt your backups with this command ...
Decompress you backup with this command ...
Restore you backup with this command ... ⚠️ warning ⚠️ 

That's the plan so far

**Comment by mablae** [comment]
I like that!

**Comment by sebastianfeldmann** [comment]
Finally this is getting merged into master!
`phpbu` 6 will support `--restore` to output a restore guide

    phpbu --restore
