### ISSUE TITLE
add support for libsodium / ext/sodium

### ISSUE THREAD

**Issue by DanielRuf** [sebastianfeldmann/phpbu#151]
It would be useful to use the much better encryption solutions by libsodium which we can easily use with https://github.com/paragonie/sodium_compat (security first).

**Comment by sebastianfeldmann** [comment]
Looks doable ;)

**Comment by peter279k** [comment]
Since the `sodium` is enabled in `php-7.0+`.

I think we can add the `ext-sodium` inside `suggest` section in `composer.json` file.

**Comment by DanielRuf** [comment]
At least PHP 7.2+ is a requirement now.
https://github.com/sebastianfeldmann/phpbu/blob/main/composer.json#L47

Just wanted to mention that some hosting providers disable this module on PHP < 8.
https://www.strato.de/faq/hosting/mit-welchen-modulen-steht-php-bei-strato-zur-verfuegung/

**Comment by sebastianfeldmann** [comment]
I haven't looked that deep into libsodium yet. As I understand it I can use PHP directly to encrypt a file with the included sodium functions in PHP >= 7.2

The challenge would be to decrypt the file again, normally all that `phpbu` does is to execute external binaries and to reverse the action for restoring or decrypting it only shows you how to do it.

If we use PHP directly to encrypt stuff we would need to actually provide the reverse (decryption) as well since there would not be a `command` that would do it. In this case `phpbu` would have to provide this functionality. This would be a completely new functionality that I would have to figure out how to integrate into `phpbu`.

Or is there a way to decrypt files on the command line that got encryption directly in PHP with `ext-sodium`?

**Comment by DanielRuf** [comment]
> Or is there a way to decrypt files on the command line that got encrypted directly in PHP with `ext-sodium`?

Good question. Do you mean something like NaCl, openssl/libressl or something else for later decryption?

I think this is not trivial as there is no native sodium implementation in many cases afaik, especially as NaCl is only a standalone library which has to be installed in most cases or implemented in solutions like the libsodium implementation in PHP.

https://de.wikipedia.org/wiki/NaCl_(Software)
https://en.wikipedia.org/wiki/NaCl_(software)

So if it is about encryption and decryption and the possibility to decrypt the files with other tools too and not just PHP, GnuPG/PGP might be probably a better solution for encryption and decryption.

**Comment by sebastianfeldmann** [comment]
So I would are the best way moving forward is to build a Composer package/binary that is able to encrypt and decrypt file with `ext-sodium` and make `phpbu` call this binary to encrypt the file and on `--restore` it will output the command to decrypt the file with the binary.

So in backup `phpbu` will execute something like.

    vendor/bin/sodicrypt -e backup.tar.gz

and on `--restore` it will output something like

    To restore run "vendor/bin/sodicrypt -d backup.tar.gz.enc"

So people are able to decrypt the backup without `phpbu` so I do not have to include the decrypt functionality into `phpbu` itself.

**Comment by DanielRuf** [comment]
This sounds like a good solution.
