### ISSUE TITLE
Simulate does not test pv on server

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#165]
The throttle depends on having the pv installed on the server, but this is not checked on simulation, so simulate works fine and then you get the error like this one on the real backup: 
```
Exception` 'RuntimeException' with message 'Command failed:
  exit-code: 127
  message:   sh: 1: pv: not found
/bin/tar: -: Cannot write: Broken pipe
/bin/tar: Error is not recoverable: exiting now

```

**Comment by sebastianfeldmann** [comment]
Not sure if this is a simulate issue.
Currently simulate doesn't check if for example `mysqldump` is installed or any other CLI tool.
I think not seeing an error on simulation is fine. Not perfect but fine.
Maybe I could add a `--check-requirements` options that does enforces that.

**Comment by planetahuevo** [comment]
Imho the simulation is something I use to know if the backup is going to
work or not. For that to be reliable, The simulation response should be the
same than doing the real backup.  If not, why bother doing a simulation at
all?

**Comment by planetahuevo** [comment]
@sebastianfeldmann can you please reconsider this? The simulation is not useful if it does not replicate what is going to happen for real.

**Comment by sebastianfeldmann** [comment]
Simulation tells you how your backup will be created.
You should make sure it will work.
Either by executing `phpbu` or by executing the commands it will output during simulation.

Besides changing the whole simulation logic this would require all relevant binaries for a simulation.
I don't like to install all binaries on my local machine or start a custom container just to simulate an execution. I want to be able to investigate this without any system requirements.

If you run it without simulation it immediately tells you where the problem is.
I see your point but changing the default simulation behavior would be a mistake in my point of view.

Like I said: I can image an additional simulation option like `--check-requirements` that would do what you ask for.
I will put it in a separate ticket as a feature request.

**Comment by planetahuevo** [comment]
As always, your approach makes much more sense than mine.
That test requeriments will work perfectly for my needs. 
Thanks!

**Comment by planetahuevo** [comment]
By the way, it is a nice to have and not an urgent feature at all.
