### ISSUE TITLE
Feature request: Add adapter YML file

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#167]
Having the option to have a YML adapter file will make easier to use PHPBU as we can use other yml files with the data without the need to duplicate the config files only for phpbu.

It is also a really easy file to use for config files. 

Thanks!

**Comment by sebastianfeldmann** [comment]
To say it politely, I don't like YAML. It is a horrible format. To process it you need an additional library.
Json and XML are supported by PHP out of the box.
So I will most likely never add YAML support to `phpbu`.
Sorry

**Comment by planetahuevo** [comment]
Fair enough.
Which format do you think is best for bash scripts?

**Comment by planetahuevo** [comment]
:)
It is the same level of complication than the backups. It uses the same
config information and that is the reason I was thinking I could save one
config file using the same format for both apps, my script and phpbu.
And I though in yml because it's used by ansible and wp cli. Wp cli is
something I use a lot and Ansible is something I am considering to
eliminate the bash scripts... :)

**Comment by sebastianfeldmann** [comment]
So you have two options

Use ansible to generate and deploy the bash and phpbu config. Then it doesn't matter that you have the same values in different files, because you manage them via ansible in a single place.
Still not perfect but acceptable in my view, since you never edit the configuration or the bash scripts by hand.

The second options is you store them in a bash friendly way so the bash script you are using can use a configuration. I don't think bash has native yaml support so maybe a simple sourcing is  enough
https://askubuntu.com/questions/743493/best-way-to-read-a-config-file-in-bash
And then write an adapter for phpbu that can read that format so you can use the values from your bash config.

I use ansible a lot so I would suggest ansible, but as easy as it is, it is another tool you have to figure out and learn to master.

**Comment by planetahuevo** [comment]
Thank you @sebastianfeldmann !

I have been investigating about Ansible and I am going to go to use it for sure. 
One personal question: You do not like YML files but you use Ansible, do you use yml with Ansible or not? I have not seen any alternative (but just starting on it).

Thanks again for you help!

**Comment by sebastianfeldmann** [comment]
Yes Ansible only works with YML
But I still like Ansible a lot, even if the YML configs drive me crazy sometimes ;)

**Comment by planetahuevo** [comment]
I have discover YML recently, so it could drive me crazy in the future. lol :)
