### ISSUE TITLE
Google drive access token

### ISSUE THREAD

**Issue by sharifzadesina** [sebastianfeldmann/phpbu#170]
Why we need to use `phpbu-google-drive` to generate access token? I think the script itself can initiate it if the file didn't exist.

**Comment by sebastianfeldmann** [comment]
The google drive authentication requires you to open a URL and authenticate the request
I do not want that kind of functionality in phpbu itself because hat would enable the phpbu app to create new credentials.
For the same reason phpbu is not able to create ssh keys or any other tokens you need to authenticate.
This keeps phpbu much more simple. There is exactly one path the application executes and it doesn't change the path depending on files or data that is available. It either works or it doesn't.

`phpbu-google-drive` is something I created just for convenience.

The question should be why is the google drive authentication so painfull ;)

**Comment by sharifzadesina** [comment]
@sebastianfeldmann Actually you already re-write `client_access.json` when the current `access_toekn` is expired, so why not just initialize it?

**Comment by sharifzadesina** [comment]
It seems there is no way to get access token without browser, this is sad. closed.

**Comment by sebastianfeldmann** [comment]
I would love to add mega support :)

**Comment by sharifzadesina** [comment]
I will try to send a PR in next few weeks 100%.
