### ISSUE TITLE
PHPBU executes no backups on localhost

### ISSUE THREAD

**Issue by gitchrisk** [sebastianfeldmann/phpbu#177]
I have a XAMPP environment with PHP 7.0. I installed PHPBU in my website project by putting the phpbu.phar and phpbu.xml files into the root directory.

My configuration:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpbu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="http://schema.phpbu.de/5.1/phpbu.xsd"
       verbose="true">
    <sync type="sftp">
        <option name="host" value="my-host"/>
        <option name="port" value="22"/>
        <option name="user" value="my-ftp-user"/>
        <option name="password" value="123456"/>
        <option name="path" value="/my/path"/>
        <option name="passive" value="true"/>
    </sync>
</phpbu>
```

I execute in my terminal:
`php phpbu.phar`

I get the following result:

```
phpbu 5.1.6 by Sebastian Feldmann and contributors.

Runtime:       PHP 7.0.6
Configuration: C:\xampp\htdocs\www\european-business-ecademy\website\main\phpbu.xml

Time: 1 second, Memory: 4.00MB

No backups executed!

```

Nothing gets backuped. How come?

**Comment by sebastianfeldmann** [comment]
You have a configuration issue, you have to specify a `<backup>` and that backup can be synced.
So your configuration structure should look something like this.
```xml
<phpbu>
  <backups>
    <!-- My backup configuration -->
    <backup>
      <!-- data to backup -->
      <source></source>
      <!-- method and place to move the stored backup to -->
      <sync></sync>
    </backup>
    <!-- followed by more backup tags if your need them -->
    <!-- ... -->
  </backups>
</phpbu>
```

So if you want to backup some directory you use the `tar` source. If you want to backup your database you use, for example, the `mysqldump` source.
If you want to backup both files and database you have to configure two `<backup>`s in your configuration file.

Be aware that on windows you can have difficulties because the required shell commands are not installed by default or are not in your environment %PATH%. So if you want to backup your MySQL database, `phpbu` has to be able to find the `mysqldump` command, if it is not in your %PATH% you can specify it in the configuration. Same for backing up a directory with `tar` the command must be installed and available for `phpbu` to execute. To install it on Windows you install git (https://git-scm.com/download/win) and use the tar command that comes with git, or you can install CYGWIN for example.

**Comment by gitchrisk** [comment]
Hi Sebastian,

thank you very much for your quick reply. I already installed GIT, in addition I just installed CYGWIN.

My new configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<phpbu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="http://schema.phpbu.de/5.1/phpbu.xsd"
       verbose="true">
    <backups>
        <source type="tar">
            <option name="path" value="/"/>
        </source>
        <sync type="sftp">
           <option name="host" value="my-host"/>
           <option name="port" value="22"/>
           <option name="user" value="my-ftp-user"/>
           <option name="password" value="123456"/>
           <option name="path" value="/my/path"/>
           <option name="passive" value="true"/>
        </sync>
    </backups>
</phpbu>
```

I executed the command via GIT BASH:
`php phpbu.phar
`
Still, I get the old message:
```
phpbu 5.1.6 by Sebastian Feldmann and contributors.

Runtime:       PHP 7.0.6
Configuration: C:\xampp\htdocs\www\european-business-ecademy\website\main\phpbu.xml

Time: 1 second, Memory: 4.00MB

No backups executed!

```
What am I missing?

**Comment by sebastianfeldmann** [comment]
You are still missing the `<backup>` tag.

`<phpbu> <backups> <backup>`

Be aware that
```xml
<option name="path" value="/"/>
```
Will backup your complete system, because "/" is the root directory of your computer not your project.
You should use something like:
```xml
<option name="path" value="./public/uploads" />
```
The source code, the assets and the configuration are hopefully stored in a git repository, so the ony files you have to care about are the files the user uploads to your website ;)
