### ISSUE TITLE
PHP Warning, PHP Parse error - v5.1.10

### ISSUE THREAD

**Issue by r6b** [sebastianfeldmann/phpbu#178]
Hi, running the latest version with the command 'php phpbu.phar' I get the following error message.

PHP Warning:  Class 'Tightenco\Collect\Support\Arr' not found in phar:///home/[redacted]/phpbu.phar/lib/tightenco/Collect/Support/alias.php on line 16
PHP Parse error:  syntax error, unexpected '=' in phar:///home/[redacted]/phpbu.phar/lib/tightenco/Collect/Support/Arr.php on line 388

**Comment by sebastianfeldmann** [comment]
Could you paste your configuration? I will try to reproduce this.

**Comment by r6b** [comment]
This is my configuration but I don't think this config matters since it can't even show the version via "phpbu --version" by erroring out before it gets to that point.

```
<?xml version="1.0" encoding="UTF-8"?>
<phpbu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="http://schema.phpbu.de/5.1/phpbu.xsd">
  <backups>
    <backup name="MySQLDatabase">
    <cleanup type="quantity">
	<option name="amount" value="10" />   
    </cleanup>
      <source type="mysqldump">
        <option name="databases" value="[redacted]"/>
        <option name="user" value="[redacted]"/>
        <option name="password" value="[redacted]"/>
      </source>
      <target dirname="/var/www/html/backup"
              filename="mysql-%Y%m%d-%H%i.sql"
              compress="gzip"/>
    </backup>
    <backup name="ImgDirectory">
    <cleanup type="quantity">
 	<option name="amount" value="10" />
    </cleanup>
    <source type="tar">
      <option name="path" value="/var/www/html/img"/>
      <option name="exclude" value="index.php"/>
    </source>
      <target dirname="/var/www/html/backup"
              filename="img-%Y%m%d-%H%i"
              compress="gzip"/>
    </backup>
  </backups>
</phpbu>

```

**Comment by sebastianfeldmann** [comment]
Thanks, will get right on it

**Comment by sebastianfeldmann** [comment]
I think you are using PHP 7.0 and one of `phpbu`s dependencies dependencies broke because it requires 7.1.

`phpbu` `7.0` => `Dropbox SDK` `7.0` => `Collection lib` `7.1` 💥 

I downgraded the dependency so `phpbu` will work with PHP 7.0 again.
You can try with the latest version 5.1.11.

Be aware that PHP 7.0 is not actively supported anymore, and even 7.1 is only getting security updates.
You can have a look at the supported versions here http://php.net/supported-versions.php

I keep the 7.0 support for semantic versioning reasons, but `phpbu` 6.0 will no longer support PHP 7.0 and php 7.1
