### ISSUE TITLE
Ability to set the path for remote cleanup

### ISSUE THREAD

**Issue by andrelopez** [sebastianfeldmann/phpbu#187]
Hi Sebastian!

Is possible to add a setting to set the remote cleanup path? I mean to don't use the same as the sync config. Also, I have one question related to the remote cleanup. Is a folder considered a file when the cleanup type is `quantity` ?

Best,

**Comment by sebastianfeldmann** [comment]
Hi,
could you elaborate a bit on the "different path" idea.
Because why should you use a different path to clean up as where you put the backups in the first place. This would only make sense if you move the backups afterwards or want to cleanup other files then backups.

Regarding the folders, no they are not treated as files. Even if you have files in the same directory structure that are no backups those will not be deleted. But be aware that the backup collectors find backup files using regular expressions, meaning if you have files in that structure that "look" similar to your backup files they will be deleted as well.

**Comment by andrelopez** [comment]
Thanks @sebastianfeldmann 

Basically, I had the next scenario:
`backup_xxxxxxx`
    ->`database_xxxxxxx.zip`
    ->`directory1_xxxxxxx.zip` 
    ->`directory2_xxxxxxx.zip` 
`backup_yyyyyyy`
    ->`database_yyyyyyy.zip`
    ->`directory1_yyyyyyy.zip` 
    ->`directory2_yyyyyyy.zip`
`backup_zzzzzzz`
    ->`database_zzzzzzz.zip`
    ->`directory1_zzzzzzz.zip` 
    ->`directory2_zzzzzzz.zip`
and so on...

What I wanted to remove is the container folders, for example, if `quantity` is 2  the `backup_zzzzzzz` folder should be deleted.

So I may need to update the folders structure to something like:
`databases`
   ->`database_xxxxxxx.zip`
   ->`database_yyyyyyy.zip`
   ->`database_zzzzzzz.zip`
`directory1`
   ->`directory1_xxxxxxx.zip`
   ->`directory1_yyyyyyy.zip`
   ->`directory1_zzzzzzz.zip`
and so on...

So for each directory, phpbu will check the quantity and remove files. Is that right?

**Comment by sebastianfeldmann** [comment]
I would suggest exactly that change
If you have a directory structure like

```
backup
    2018
         backup12.tar.gz
    2019
         backup01.tar.gz
         backup02.tar.gz
```

If phpbu deletes the `backup12.tar.gz` the `2018` directory will not be removed.
So over time you end up with a "lot" of empty directories.
This approach makes sense if you keep many backups for a long time.

If you roughly keep 100 backups it's a best practice to keep them in a single folder if you are using classic directory structures, if you are using cloud storages you don't have to care as much, because they don't work in terms of directory structures most of the time.

**Comment by andrelopez** [comment]
Thanks @sebastianfeldmann I'll give a try
