### ISSUE TITLE
Usage of PEAR package achive_tar

### ISSUE THREAD

**Issue by bavarianbytes** [sebastianfeldmann/phpbu#200]
Hi,
as my hoster (all-inkl.com) can only call .php scripts as cronjobs (no command line cronjobs) i created a php script that calls PHPBU via `exec`.

But for `exec` the usage of `/bin/tar` is not allowed (permission denied). Is it possible to use the PEAR package `archive_tar` instead, as this is installed?

I also tried to use `rsync` (that as also available vie exec), but PHPBU seams tries to create a tar file afterwords:
```
<source type="rsync">
	<option name="path" value="/www/htdocs/w00****/path" />
	<option name="exclude" value="typo3temp,typo3conf/l10n,fileadmin/_processed_" />
	<option name="isDirSync" value="true" />				
</source>
<target dirname="/www/htdocs/w00****/_backups" filename="files-%Y%m%d-%H%i" />
```

**Comment by sebastianfeldmann** [comment]
Hi,
`phpbu` is build around the notion that a backup (in the end) is one file, so if your backup of choice (e.g. rsync) creates a directory `phpbu` will try to `tar` your backup into a single file, even if you have not configured compression like `gzip` or `bzip2`.

This is done because of the post processing for syncing and cleaning up.

Currently a fallback to php implementations of binaries like `archive_tar` is not possible :( 

Maybe talk to your hoster, if `rsync` is available there should be no reason to not use `tar` as well.

**Comment by bavarianbytes** [comment]
Ok, thanks. I wrote the hoster to see if they can enable it.
