### ISSUE TITLE
No documentation for array of cleanups

### ISSUE THREAD

**Issue by riefive** [sebastianfeldmann/phpbu#27]
There is no documentation for array of cleanups on json. Not like tag of checks:

```javascript
"checks": [
        {
          "type": "sizemin",
          "value": "10MB"
        }
      ]

```
Here is my config of cleanup, but not work and error. If i change "cleanups" to "cleanup" my backup is not running.

```javascript
"cleanups": [
        {
          "type": "capacity",
          "options": {"size": "200M"}
        },
        { 
         "type": "outdated",
          "options": {"older": "2W"}
        }
      ]
```
is possible make cleanup array json like check?

**Comment by sebastianfeldmann** [comment]
Hi, currently it's not possible to configure multiple cleanup strategies for a single '**backup**'.
This is because they could conflict each other and you would have to configure a conflict behaviour.
I opted to not go for this kind of complexity.
But each '**backup**' can have its own cleanup strategy.
So if you backup some database and some files, you can cleanup those differently.
Does this clear things up a bit?
Let ne know if I need more details, or realy need multiple cleanup strategies for a single backup.

**Comment by riefive** [comment]
Hi, Sebastian. Your explanation is clear. I have changed my config with single cleanup on every backup. Trims for awesome backup tools :)

**Comment by sebastianfeldmann** [comment]
Great ;)
