### ISSUE TITLE
phpbu --restore error: 'mysql' was nowhere to be found please specify the correct path

### ISSUE THREAD

**Issue by hafiyzaid** [sebastianfeldmann/phpbu#282]
Hi. Thank you for the idea. I have tried the backup to the amazon s3 and it is successfully executed.

Now I have the problem to restore. I tried the "phpbu --restore" command and the error appear " 'mysql' was nowhere to be found please specify the correct path". Would you explain more details how to use restore from phpbu?

**Comment by sebastianfeldmann** [comment]
So, `phpbu` will not restore backups directly.

`phpbu` will only show you the commands you have to execute in order to restore you backup but you will still have to execute them manually.

`phpbu` will only display restore commands if the sources support the `--restore` feature. At this point not all of them do.

Your command fails, because even if `phpbu` is not executing anything it still tries to create commands as accurate as possible. So it will try to use the right path to you commands etc. If your local machine has no `mysql` command installed the restore command will fail.

You can run the `--restore` command without any issues on the same machine you are creating the backup, since it will not execute, change or really restore anything.
