### ISSUE TITLE
Call to undefined function JmesPath\mb_strlen()

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#322]
I am getting this error: Not sure where to start to debug:
```
PHP Fatal error:  Uncaught Error: Call to undefined function JmesPath\mb_strlen() in phar:///usr/local/bin/phpbu/lib/mtdowling/jmespath.php/Lexer.php:343
Stack trace:
#0 phar:///usr/local/bin/phpbu/lib/mtdowling/jmespath.php/Parser.php(76): JmesPath\Lexer->tokenize()
#1 phar:///usr/local/bin/phpbu/lib/mtdowling/jmespath.php/AstRuntime.php(42): JmesPath\Parser->parse()
#2 phar:///usr/local/bin/phpbu/lib/mtdowling/jmespath.php/Env.php(33): JmesPath\AstRuntime->__invoke()
#3 phar:///usr/local/bin/phpbu/lib/aws-sdk/Endpoint/PartitionEndpointProvider.php(117): JmesPath\Env::search()
#4 phar:///usr/local/bin/phpbu/lib/aws-sdk/Endpoint/PartitionEndpointProvider.php(99): Aws\Endpoint\PartitionEndpointProvider::mergePrefixData()
#5 phar:///usr/local/bin/phpbu/lib/aws-sdk/ClientResolver.php(704): Aws\Endpoint\PartitionEndpointProvider::defaultProvider()
#6 phar:///usr/local/bin/phpbu/lib/aws-sdk/ClientResolver.php(286): Aws\ClientResolver::_default_endpoint_provider()
#7 phar:///usr/local/bin/phpbu/lib/aws-sdk/AwsClient.php(187): Aws\Cl in phar:///usr/local/bin/phpbu/lib/mtdowling/jmespath.php/Lexer.php on line 343
```

**Comment by planetahuevo** [comment]
possible solution here: 
https://stackoverflow.com/questions/6419102/fatal-error-call-to-undefined-function-mb-strlen

**Comment by hype09** [comment]
Hm, this puzzles me a bit. Can you provide more information on the type of environment you run phpbu in: PHP version, OS, Shared Hosting, phpbu version, ...?

This usage of `mb_strlen` comes from a transitive dependency: phpbu uses `aws/aws-sdk-php`, which uses `mtdowling/jmespath.php`, which uses `mb_strlen`. However, that last one also requires `symfony/polyfill-mbstring`, which _should_ transparently add the function in the global namespace, if it doesn't exist. So I am wondering how we're even getting to this message...

**Comment by planetahuevo** [comment]
Well, is a VPS with docker and no php server. So the php installed there is the default ubuntu one, which lacks the mbstring. 
Installing `apt-get install php7.4-mbstring` solve the issue and works, but yeah, I wondered the same thing.

**Comment by hype09** [comment]
Actually, I believe I have found the reason: The Polyfill seems not to be included in the final `phpbu.phar` distribution file:

```shell
phar list -f phpbu.phar | grep polyfill-mbstring
# 0 results
```

I believe the Phar file is built by copying dependencies over via a "whitelist": https://github.com/sebastianfeldmann/phpbu/blob/b65da0cf15ce0989eef6f2f0eb6291821a6f2884/build.xml#L453-L461

E.g.: The current distribution only contains `symfony/options-resolver`, but not the other `symfony/*` dependencies, such as the polyfill:

- deprecation-contracts
- polyfill-ctype
- polyfill-mbstring
- polyfill-php80
- process
- var-dumper

I am not sure why the dependencies are copied one-by-one, rather than adding all of them. Perhaps distribution size? But even then I would guess adding everything and then removing the ones that are definitely _not_ needed (aka. blacklist rather than whitelist) would make for more stable release package while keeping release sizes reasonable.

**Comment by sebastianfeldmann** [comment]
Yes the main reason for the whitelist was file size at some point.
But I think changing it to a blacklist would be the better option.
That does not remove the burden of knowing every dependency that goes into the PHAR.
The Symfony polyfills are a good example. Including the classes into the PHAR is not enough.
The polyfill setup hast to be manually called within the PHAR

```php
    // load the symfony polyfills
    require __PHPBU_PHAR_ROOT__ . '/lib/symfony/polyfill-ctype/bootstrap.php';
    require __PHPBU_PHAR_ROOT__ . '/lib/symfony/polyfill-mbstring/bootstrap.php';
    require __PHPBU_PHAR_ROOT__ . '/lib/symfony/polyfill-php80/bootstrap.php';
```

I think [470ab12](https://github.com/sebastianfeldmann/phpbu/commit/470ab12cad6f3d9a2d7ca2dccde7a8d71e4016c3) fixes the issue
