### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by OpenSourceSimon** [sebastianfeldmann/phpbu#365]
I just came across this amazing project but it'd be easier to deploy this with Docker. Is that possible or what would it require to add Docker support? I'd love to help with the development!

**Comment by sebastianfeldmann** [comment]
In order to run it within a Docker container you have to setup a container that can run PHP and has network access to all the services you want to backup.
You would need to "install" `phpbu` inside the container and then you can execute it with `docker run ...` 
Soshould not be too much trouble to set it up.
