### ISSUE TITLE
delete old backups from remote storages?

### ISSUE THREAD

**Issue by sergejkaravajnij** [sebastianfeldmann/phpbu#6]
I started to use _phpbu_ for backup databases from my projects some days ago.

Locally all work well and old backups have been deleting normally.

But in remote storage I have all backups from the beginning.
I use _copy.com_ as remote.

Is it normal?
Are you going to make deleting old backups from remotes?

**Comment by sebastianfeldmann** [comment]
For now phpbu *cleanup* tasks only delete local backups.
The only exception so far is the *rsync* sync, that could be configured with *--delete* to remove remote backups as well.
Removing remote backups could get crazy complicated because the local backup path does in no way correlate with the remote backup path. So there has to be a *local-path* => *remote-path* translation.
Not impossible, but right now this is not on my "roadmap".

**Comment by sergejkaravajnij** [comment]
Hi!

I've made remote deleting for copycom.

May be not so nice, but working solution.

You can see it https://github.com/sergejkaravajnij/phpbu/commit/a761b50949151af33aa30ff9a9f060343e3054f4

**Comment by sebastianfeldmann** [comment]
I'm currently on vacation and the internet here is pretty bad, so i will have a look at this in the next couple of days :)
