### ISSUE TITLE
PHP 5.5 required because of aws/aws-sdk-php

### ISSUE THREAD

**Issue by xoul** [sebastianfeldmann/phpbu#65]
Running phpbu as suggested would return:

```
# php phpbu.phar --version
PHP Parse error:  syntax error, unexpected '$value' (T_VARIABLE) in phar:///home/daghemo/phpbu.phar/lib/aws-sdk/functions.php on line 36
```

Cloning the repo and building with Composer would result in:

```
# php composer.phar install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - aws/aws-sdk-php 3.18.9 requires php >=5.5 -> your PHP version (5.4.16) does not satisfy that requirement.
[...]
```

Modifying composer.json to require only 2.8 (actually 2.8.30 right now) would solve the problem.
Please note that RHEL/CentOS come with PHP 5.4 out of the box.

**Comment by sebastianfeldmann** [comment]
If installed via composer phpbu is currently suggesting AWS 3.10 but you can still use version 2.x
with the `amazons3-v2` sync.

```xml
<sync type="amazons3-v2">
  ...
</sync>
```

If you are using the PHAR version there is no such option, because phpbu comes bundled with AWS version 3.10 so PHP 5.5 is a hard requirement to run it.
You can still use an older PHAR version of phpbu.
Here is a list of all phpbu releases so far http://phar.phpbu.de
You can use a 2.x version and should be fine.

Please note, that PHP 5.4 doesn't even get security fixes any more and security support for 5.5 is going to end in a couple of days. So it's safe zu say, that PHP 5.6 should be the minimum version you are running.

I know a lot of Linux distributions come with outdated software versions but for most of them there are up to date third party packages available. I'm a Debian user so sadly I can't help you with CENTOS but I'm quite certain there is an easy solution available.

Just to give you a little forecast, the next major version of PHPBU (4.x) will require PHP 5.6.

I'm sorry, that doesn't solve you problem at all. But the sad and hard truth is:
"Upgrade your PHP version" 

Cheers Sebastian
